services:
  pdf:
    build:
      context: .
      dockerfile: ${DOCKER_FILE}
      args:
      - HTML=${HTML}
      - MOUNT_POINT=${MOUNT_POINT}
    working_dir: /tmp/
    command: >
        /chrome-headless
          --no-sandbox
          --headless
          --disable-gpu
          --no-pdf-header-footer
          --no-margins
          --run-all-compositor-stages-before-draw
          --print-to-pdf=${PDF}
          ${MOUNT_POINT}
    volumes:
        - ./resumes:/tmp/resumes
        - ./assets:/tmp/assets

    # Interactive Shell for Troubleshooting
    #stdin_open: true # docker run -i
    #tty: true        # docker run -t
