---
meta:
  Author: "Wes Henderson"
  Description: "The personal webpage of Wes Henderson."
  Icon: "https://www.weshenderson.info/assets/images/skull.ico"
  Twitter: "NecromancerTux"
  Tags:
    - "Wes"
    - "Henderson"
    - "Wes Henderson"
    - "Linux"
    - "Linux Nerd"
    - "San Antonio"
    - "Texas"
  googleAnalytics: "G-1HMXV18Z9V"
Page:
  Color:
    Background: 'black'
    Font: '#ff00fb'
    Clicked-Link: 'turquoise'
  Font: 'Sans-serif'
  Borders: False
Header:
  Title: "Father, Traveler, Problem Solver, & Linux Nerd"
Image:
  Path: "https://www.weshenderson.info/assets/images/necrux-scaled.webp"
  AltText: "Necrux the Octocat!"
Body:
  Blog: "https://necrux.com"
  GitHub: "https://github.com/necrux"
  LinkedIn: "https://www.linkedin.com/in/wes-henderson"
  GPG Key: "docs/wes-henderson-public-key.txt"
  Keybase: "https://keybase.io/necrux"
  Twitter: "https://twitter.com/necromancertux"
  Resume: "/resume.html"
Footer:
  Title: ""
  CombinedTitle:
    Title: "529 Donation Links: "
    Links:
      Kairi: "https://go.fidelity.com/jnz1ko"
      Kalel: "https://go.fidelity.com/tsrje3"
      Cairo: "https://go.fidelity.com/6pgu38"
    FS: " | "
  Copyright: True
