---
meta:
  siteAuthor: "Wes Henderson"
  siteDescription: "The personal webpage of Wes Henderson."
  siteIcon: "https://www.weshenderson.info/assets/images/skull.ico"
  siteTwitter: "NecromancerTux"
  siteTags:
    - "Wes"
    - "Henderson"
    - "Wes Henderson"
    - "Linux"
    - "Linux Nerd"
    - "San Antonio"
    - "Texas"
  googleAnalytics: "G-1HMXV18Z9V"
pageLayout:
  color:
    background: 'black'
    font: '#ff00fb'
    clickedLink: 'turquoise'
  font: 'Sans-serif'
  borders: false
content:
  header:
  - "Father, Traveler, Problem Solver, & Linux Nerd"
  heroImage:
    path: "https://www.weshenderson.info/assets/images/necrux-scaled.webp"
    altText: "Necrux the Octocat!"
  body:
  - Blog: "https://necrux.com"
    GitHub: "https://github.com/necrux"
    LinkedIn: "https://www.linkedin.com/in/wes-henderson"
    GPG Key: "assets/txt/wes-henderson-public-key.txt"
    Keybase: "https://keybase.io/necrux"
    Twitter: "https://twitter.com/necromancertux"
    Resume: "/resumes/resume.html"
  footer:
    - title: "529 Donation Links: "
      combineTitle: true
      links:
      - Kairi: "https://go.fidelity.com/jnz1ko"
        Kalel: "https://go.fidelity.com/tsrje3"
        Cairo: "https://go.fidelity.com/6pgu38"
      fs: " | "
  copyright: true

