---
meta:
  theme: "elegant"
  siteAuthor: "Wes Henderson"
  siteDescription: "The resume of Wes Henderson."
  siteIcon: "https://www.weshenderson.info/assets/images/resume.ico"
  siteThumbnail: "https://www.weshenderson.info/assets/images/necrux-scaled.webp"
  siteTwitter: "NecromancerTux"
  siteTags:
    - "Wes"
    - "Henderson"
    - "Wes Henderson"
    - "Systems Engineer"
    - "Resume"
    - "San Antonio"
    - "Texas"
  googleAnalytics: "G-1HMXV18Z9V"
  emailSubject: "You're hired! ;)"
basics:
  name: "Wes Henderson"
  label: "Systems Engineer"
  image: "https://www.weshenderson.info/assets/images/necrux-scaled.webp"
  email: "whendersonii@gmail.com"
  phone: "(210) 589-0628"
  url: "https://weshenderson.info"
  summary: "I am a community oriented Linux nerd with more than a decade of IT experience and a penchant for automation, documentation, and mentoring. I am keenly aware of operations and ever mindful of opportunities for process improvement; I believe that continuous improvement is paramount for any organization. The key to maintaining continuous improvement is to build and maintain a strong team through constant, organic training."
  location:
    city: "San Antonio"
    countryCode: "US"
  profiles:
    - network: twitter
      url: https://twitter.com/necromancertux
      username: NecromancerTux
    - network: github
      url: https://github.com/necrux
education:
- institution: "Northwest Vista College"
  url: "https://www.alamo.edu/nvc/"
  area: "Computer Forensics"
  studyType: "Associate of Applied Science"
  startDate: "2010-01-01"
  endDate: "2012-05-15"
  score: "4.0"
  location: "San Antonio, Texas"
  courses:
    - "Marketable Skills Achievement Award: Linux RHCT"
    - "Marketable Skills Achievement Award: Information Security & Assurance"
certificates:
- name: "Certified Solutions Architect"
  date: "2017-01-01"
  issuer: "AWS"
  url: "https://aws.amazon.com/certification/"
  license: "AWS-ASA-29789"
- name: "Certified Engineer"
  date: "2016-01-01"
  issuer: "Red Hat"
  url: "https://www.redhat.com/en/services/training-and-certification"
  license: "130-119-274"
- name: "Certified System Admin"
  date: "2013-01-01"
  issuer: "Red Hat"
  url: "https://www.redhat.com/en/services/training-and-certification"
  license: "130-119-274"
- name: "Cert 1"
  date: "2012-01-01"
  issuer: "Linux Professional Institute"
  url: "https://www.lpi.org/"
  license: "LPI000250530"
- name: "Certified Linux Admin"
  date: "2012-01-01"
  issuer: "Novell"
  url: ""
  license: "10176504"
- name: "DC Technical Specialist"
  date: "2012-01-01"
  issuer: "Novell"
  url: ""
  license: "10176504"
- name: "Linux+"
  date: "2012-01-01"
  issuer: "CompTIA"
  url: "https://www.comptia.org/"
  license: "COMP001007825623"
- name: "Security+"
  date: "2010-01-01"
  issuer: "CompTIA"
  url: "https://www.comptia.org/"
  license: "COMP001007825623"
- name: "Network+"
  date: "2010-01-01"
  issuer: "CompTIA"
  url: "https://www.comptia.org/"
  license: "COMP001007825623"
- name: "A+"
  date: "2008-01-01"
  issuer: "CompTIA"
  url: "https://www.comptia.org/"
  license: "COMP001007825623"
skills:
- name: "DevOps"
  level: "Master"
  keywords:
    - Research
    - Linux
    - AWS
    - GCP
    - GitHub
    - Terraform / CloudFormation
    - Ansible / Chef / Puppet
- name: "Leadership"
  level: "Proficient"
  keywords:
    - Mentoring
    - Documentation
- name: "Programming"
  level: "Proficient"
  keywords:
    - Python
    - Bash
    - Powershell
Experience:
  1:
    Company: "Salesforce"
    Title: "Lead Systems Engineer"
    Dates: "November 2019-Present"
    Summary:
      - "Led a small team on our ‘Bring Your Own Key’ (BYOK) initiative; this product allowed customers to fully own the keys their databases were encrypted with and represented $6 million in recurring revenue for Pardot."
      - "Helped to identify and deploy cost saving measures in our public cloud infrastructure, representing a savings of $3 million dollars annually."
      - "Led multiple teams across multiple business units in order to meet deployment deadlines."
      - "Built a bespoke tooling pipeline for the SRE team, allowing tools to be created and shared widely while circumventing common pitfalls around such tooling, e.g. tribal knowledge resulting in decreased visibility and adoption."
      - "Built a CLI tool to rapidly manage asynchronous jobs, greatly decreasing response time while increasing visibility."
  2:
    Company: "TrueAbility"
    Title: "Deployment Engineer"
    Dates: "December 2017-November 2019"
    Summary:
      - "Mentored junior team members and built pathways from support to engineering."
      - "Helped many top companies build, deploy, and grade their performance based assessments."
      - "Acted as a consultant on exam creation and deployment."
      - "Created bespoke environments/grading via Bash and Powershell, primarily."
      - "Contributed to the underlying codebase where applicable."
      - "Maintained the AWS and GCP infrastructure for internal tooling and exams respectively."
  3:
    Company: "Rackspace Hosting"
    Title: "DevOps Engineer"
    Dates: "May 2013-December 2017"
    Summary:
      - "Architect and deploy scalable cloud solutions for customers in an AWS ecosystem via CloudFormation."
      - "Design for customers’ regulatory requirements (e.g. PCI, HIPAA, etc)."
      - "Educate customers on distributed computing principles and CI/CD solutions."
      - "Collaborate with team members via GitHub."
      - "Wrote a Python framework to automate the build process."
      - "Created custom tooling in Bash and Python."
      - "Active contributor to both the internal Rackspace wiki and public blog."
