---
meta:
  siteAuthor: "Wes Henderson"
  siteDescription: "The personal webpage of Wes Henderson."
  siteIcon: "assets/images/skull.ico"
  siteImage: "assets/images/necrux-scaled.webp"
  siteTags:
    - "Wes"
    - "Henderson"
    - "Wes Henderson"
    - "Linux"
    - "Linux Nerd"
    - "San Antonio"
    - "Texas"
    - "Systems Engineer"
    - "RHCE"
  googleAnalytics: "G-1HMXV18Z9V"
pageLayout:
  color:
    background: "black"
    font: "green"
    clickedLink: "#5cdff2"
    primary: "green"
    secondary: "#8b5bb5"
    tertiary: "grey"
  font:
    googleFont: false
    fontLink: "https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@600&display=swap"
    name: "monospace"
    size: 3
content:
  header: "#!"
  heroImage:
    path: "assets/images/necrux-scaled-black-bg.webp"
    altText: "Necrux the Octocat!"
  resume: "resumes/resume.html"
  prompt: "[necrux@system]:~$"
  name: "Wes Henderson"
  title: "Staff Systems Engineer"
  site: "weshenderson.info"
  description: "> Father, Traveler, Problem Solver, 3D Printer Enthusiast, & Linux Nerd"
  pid: "80085"
  sysinfo:
    enable: true
    heading: "[system]"
    table:
      uptime: "40y"
      shell: "/bin/bash"
      editor: "vim"
      distro: "Red Hat 10"
  links:
    Blog: "https://necrux.com"
    GitHub: "https://github.com/necrux"
    LinkedIn: "https://www.linkedin.com/in/wes-henderson"
    GPG Key: "assets/txt/wes-henderson-public-key.txt"
    Keybase: "https://keybase.io/necrux"
    Bluesky: "https://bsky.app/profile/necrux.bsky.social"
    Maker World: "https://makerworld.com/en/@necrux"
  donations:
    enable: true
    title: "529 Donation Links"
    fieldSeparator: "|"
    links:
      Kairi: "https://go.fidelity.com/jnz1ko"
      Kalel: "https://go.fidelity.com/tsrje3"
      Cairo: "https://go.fidelity.com/6pgu38"
  copyright: true
