#!/usr/bin/env bash
set -eo pipefail

INDEX='index.html'
INDEX_CSS='assets/css/main.css'
RESUME='resumes/resume.html'
PDF='resumes/resume.pdf'
JSON='resumes/resume.json'
BASE_PATH="$(git rev-parse --show-toplevel)"
FILE_CHECK=(configs/
            alea
            templates/
            assets)

if [ -f /wsl ]; then
    COMPOSE_BIN='/mnt/c/Program Files/Docker/Docker/resources/bin/docker-compose'
else
    COMPOSE_BIN='docker-compose'
fi

function alea {
    for file in ${FILE_CHECK[@]}; do
        if git status --porcelain | grep -q ${file}; then
            pushd "${BASE_PATH}" &>/dev/null
                ./alea.py --index --resume --json
                git add ${INDEX}
                git add ${INDEX_CSS}
                git add ${RESUME}
                git add ${JSON}
            popd &>/dev/null
            break
        fi
    done
}

function create-pdf-resume {
    if git status --porcelain | grep -q "${RESUME}"; then
        pushd "${BASE_PATH}" &>/dev/null
	    export TMP="resumes/resume_tmp_pdf.html"
	    export OUTPUT=${PDF}
            cp ${RESUME} ${TMP}
            sed -i 's@<h3><a id="pdf" href="resume.pdf">Download PDF</a></h3>@@g' ${TMP}
	    "${COMPOSE_BIN}" up
            rm -f ${TMP}
            git add ${PDF}
        popd &>/dev/null
    fi
}

function check-code {
    echo 'Linting code: pylint.'
    pylint $(git ls-files '*.py')
}

check-code
alea
create-pdf-resume
