#!/usr/bin/env bash

set -eo pipefail

RESUME='resume.html'
PDF='docs/Resume.pdf'
BASE_PATH="$(git rev-parse --show-toplevel)"
SITE_CHECK=(content.yaml
            resume.yaml
            alea
            templates
            assets)

function alea {
    for file in ${SITE_CHECK[@]}; do
        if git status --porcelain | grep -q ${file}; then
            pushd "${BASE_PATH}" &>/dev/null
                ./alea.py --index --resume
                git add index.html
                git add assets/css/main.css
                git add ${RESUME}
                if [ -f ${KONAMI} ]; then
                    git add ${KONAMI}
                fi
            popd &>/dev/null
            break
        fi
    done
}

function create-pdf-resume {
    if git status --porcelain | grep -q "${RESUME}"; then
        pushd "${BASE_PATH}" &>/dev/null
            local TMP='resume_pdf.html'
            cp ${RESUME} ${TMP}
            sed -i 's@<h3><a id="pdf" href="docs/Resume.pdf">Download PDF</a></h3>@@g' ${TMP}
            /usr/bin/google-chrome \
                --headless \
                --disable-gpu \
                --no-pdf-header-footer \
                --no-margins \
                --run-all-compositor-stages-before-draw \
                --print-to-pdf=${PDF} \
                file://${BASE_PATH}/${TMP}
            rm -f ${TMP}
            git add ${PDF}
        popd &>/dev/null
    fi
}

alea
create-pdf-resume
