# Generate all resume and website artifacts.

name: Alea

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository.
      uses: actions/checkout@v4
    - name: Set up Python.
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies.
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Check for website changes.
      id: website_updates
      uses: dorny/paths-filter@v3
      with:
        filters: |
          specific_file:
            - 'configs/website.yaml'
            - 'templates/*index*'
            - 'templates/*website*'
            - 'templates/main.css.j2'
            - 'templates/.build.metadata'
    - name: Check for resume changes.
      id: resume_updates
      uses: dorny/paths-filter@v3
      with:
        filters: |
          specific_file:
            - 'configs/resume.yaml'
            - 'templates/*resume*'
            - 'templates/.build.metadata'
    - name: Updating website artifacts -- HTML, CSS
      if: steps.website_updates.outputs.specific_file == 'true'
      run: python ./alea.py --website
    - name: Updating resume artifacts -- JSON, HTML, MD, DOCX
      if: steps.resume_updates.outputs.specific_file == 'true'
      run: python ./alea.py --resume
    - name: Updating resume artifact -- PDF
      if: steps.resume_updates.outputs.specific_file == 'true'
      run: |
        source .build.parameters

        cp ${RESUME} ${TMP}
        sed -i 's@<!-- H-ONLY -->.*<!-- /H-ONLY -->@@g' ${TMP}

        docker compose --env-file .build.parameters up --build
        rm -f ${TMP}
    - name: Inject website build metadata.
      if: steps.website_updates.outputs.specific_file == 'true'
      run: |
        FILES=(index.html assets/css/main.css)
        DATE=$(TZ="America/Chicago" date "+%Y-%m-%d %I:%M:%S %p %Z")
        sed -i "s/ALEA_BUILD/${GITHUB_RUN_NUMBER}/g" ${FILES[@]}
        sed -i "s/ALEA_RUN_ID/${GITHUB_RUN_ID}/g" ${FILES[@]}
        sed -i "s/ALEA_ATTEMPT/${GITHUB_RUN_ATTEMPT}/g" ${FILES[@]}
        sed -i "s/ALEA_COMMIT/${GITHUB_SHA}/g" ${FILES[@]}
        sed -i "s/ALEA_DATE/${DATE}/g" ${FILES[@]}
    - name: Inject resume build metadata.
      if: steps.resume_updates.outputs.specific_file == 'true'
      run: |
        FILES=(resumes/resume.html resumes/resume.md resumes/resume.json)
        DATE=$(TZ="America/Chicago" date "+%Y-%m-%d %I:%M:%S %p %Z")
        sed -i "s/ALEA_BUILD/${GITHUB_RUN_NUMBER}/g" ${FILES[@]}
        sed -i "s/ALEA_RUN_ID/${GITHUB_RUN_ID}/g" ${FILES[@]}
        sed -i "s/ALEA_ATTEMPT/${GITHUB_RUN_ATTEMPT}/g" ${FILES[@]}
        sed -i "s/ALEA_COMMIT/${GITHUB_SHA}/g" ${FILES[@]}
        sed -i "s/ALEA_DATE/${DATE}/g" ${FILES[@]}
        python ./alea.py --pdf
    - name: Commit and Push Artifact(s).
      run: |
        git config --global user.name "alea[bot]"
        git config --global user.email "alea[bot]@users.noreply.github.com"

        git add index.html
        git add assets/css/
        git add resumes/

        if ! git diff --cached --quiet; then
          git commit -m "alea: artifact generation [skip ci]"
          git push
        else
          echo "No changes detected in the artifact."
        fi

    - name: Update Resume Gist.
      uses: exuanbo/actions-deploy-gist@v1
      if: steps.resume_updates.outputs.specific_file == 'true'
      with:
        token: ${{ secrets.GIST_TOKEN }}
        gist_id: 47c721cc5ac327c7acc1654fb822005b
        file_path: resumes/resume.json
