# Generate all resume and website artifacts.

name: Validate Schema - Resume

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository.
      uses: actions/checkout@v4

    - name: Check for resume changes.
      id: resume_updates
      uses: dorny/paths-filter@v3
      with:
        filters: |
          specific_file:
            - 'configs/resume.yaml'

    - name: Updating resume artifacts -- JSON, HTML, MD, DOCX, PDF
      if: steps.resume_updates.outputs.specific_file == 'true'
      run: |
        python ./alea.py --validate --resume
